# Generated by Django 4.1.4 on 2022-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_alter_tasktracker_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3),
        ),
    ]
